from typing import Protocol

from app.db import SensorModel


class SensorRepository(Protocol):
    def add(self, sensor_id: str, sensor_type: str) -> SensorModel: ...
    def get_by_sensor_id(self, sensor_id: str) -> SensorModel | None: ...
    def list(self, limit: int = 50, offset: int = 0) -> list[SensorModel]: ...
    def update(self, sensor_id: str, sensor_type: str | None = None) -> SensorModel | None: ...
    def deactivate(self, sensor_id: str) -> bool: ...
